apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium
  template:
    metadata:
      labels:
        app: selenium
    spec:
      containers:
        - name: selenium
          image: selenium/standalone-chrome:latest
          ports:
            - containerPort: 4444
            - containerPort: 7900
---
apiVersion: v1
kind: Service
metadata:
  name: selenium
spec:
  selector:
    app: selenium
  ports:
    - name: webdriver
      port: 4444
      targetPort: 4444
    - name: novnc
      port: 7900
      targetPort: 7900

